import { defineConfig } from "tinacms";

const branch = "main";

export default defineConfig({
  branch,
  clientId: "", // Will be generated by TinaCloud
  token: "", // Will be generated by TinaCloud
  build: {
    outputDirectory: "admin",
    publicEnv: ["NEXT_PUBLIC_TINA_CLIENT_ID"],
  },
  media: {
    tina: {
      mediaRoot: "assets/images/portfolio",
      targetDir: "assets/images/portfolio",
    },
  },
  schema: {
    collections: [
      {
        name: "collections",
        label: "Portfolio Collections",
        path: "_collections",
        format: "json",
        ui: {
          itemProps: (item) => ({ label: item?.title || "Collection" }),
        },
        fields: [
          {
            type: "string",
            name: "title",
            label: "Collection Title",
            ui: { description: "e.g. Urban Infinity Pool" },
          },
          {
            type: "string",
            name: "slug",
            label: "Slug",
            ui: {
              description:
                "Must match the slug used in the Portfolio Page order list, e.g. urban",
            },
          },
          {
            type: "object",
            list: true,
            name: "images",
            label: "Images",
            ui: { itemProps: (item) => ({ label: item?.image || "Image" }) },
            fields: [
              {
                type: "image",
                name: "image",
                label: "Image",
              },
            ],
          },
          {
            type: "object",
            list: true,
            name: "description",
            label: "Description",
            ui: {
              itemProps: (item) => ({ label: item?.text?.substring(0, 50) || "Paragraph" }),
            },
            fields: [
              {
                type: "rich-text",
                name: "text",
                label: "Text",
                ui: {
                  description:
                    "Select a word or sentence and click Bold to emphasize just that part.",
                },
              },
              {
                type: "string",
                name: "font_family",
                label: "Font",
                options: [
                  { label: "Use Site Default", value: "default" },
                  { label: "Playfair Display", value: "playfair" },
                  { label: "Montserrat", value: "montserrat" },
                  { label: "Poppins", value: "poppins" },
                  { label: "Merriweather", value: "merriweather" },
                  { label: "Lato", value: "lato" },
                ],
                ui: { component: "select" },
              },
              {
                type: "string",
                name: "text_size",
                label: "Size",
                options: [
                  { label: "Use Site Default", value: "default" },
                  { label: "Small", value: "small" },
                  { label: "Medium", value: "medium" },
                  { label: "Large", value: "large" },
                ],
                ui: { component: "select" },
              },
              {
                type: "string",
                name: "text_color",
                label: "Color",
                options: [
                  { label: "Use Site Default", value: "default" },
                  { label: "Black", value: "black" },
                  { label: "Charcoal", value: "charcoal" },
                  { label: "Grey", value: "grey" },
                ],
                ui: { component: "select" },
              },
              {
                type: "string",
                name: "text_color_custom",
                label: "Custom Color (Optional)",
                ui: {
                  description:
                    "Paste a hex color code here (e.g., #ffffff for white, #ff0000 for red) or leave blank",
                },
              },
            ],
          },
          {
            type: "string",
            name: "location",
            label: "Location",
          },
          {
            type: "string",
            name: "year",
            label: "Year",
          },
          {
            type: "string",
            name: "type",
            label: "Type",
          },
          {
            type: "string",
            name: "accent_color",
            label: "Accent Panel Color",
            ui: {
              description:
                "The color behind the title/description panel on this collection's page. Leave blank to use the site's usual beige.",
            },
          },
          {
            type: "string",
            name: "lightbox_color",
            label: "Lightbox Background Color",
            ui: {
              description:
                "The background behind a photo when you click it to view it full-size on this collection's page. Pick a LIGHT color — the close button and arrows are dark and become hard to see on a dark background.",
            },
          },
        ],
      },
      {
        name: "portfolio",
        label: "Portfolio Page",
        path: "_content/portfolio.json",
        format: "json",
        ui: { previewSrc: "/pages/portfolio.html" },
        fields: [
          {
            type: "object",
            list: true,
            name: "collections",
            label: "Collections",
            ui: {
              itemProps: (item) => ({ label: item?.title || "Collection" }),
            },
            fields: [
              {
                type: "string",
                name: "title",
                label: "Title",
              },
              {
                type: "string",
                name: "slug",
                label: "Slug",
                ui: {
                  description:
                    "Must match the slug on the corresponding entry in Portfolio Collections, e.g. urban",
                },
              },
              {
                type: "image",
                name: "thumbnail",
                label: "Thumbnail",
                ui: { description: "The image shown on the portfolio grid tile" },
              },
            ],
          },
        ],
      },
      {
        name: "about-marie",
        label: "About Marie",
        path: "_content/about-marie.json",
        format: "json",
        ui: { previewSrc: "/pages/about-marie.html" },
        fields: [
          {
            type: "object",
            list: true,
            name: "sections",
            label: "Sections",
            ui: {
              itemProps: (item) => ({ label: item?.heading || "Section" }),
              description: "Alternates photo left/right automatically based on position in this list.",
            },
            fields: [
              {
                type: "string",
                name: "heading",
                label: "Heading",
                ui: {
                  description: "Leave blank for a section with no heading, e.g. ABOUT or MEET MARIE",
                },
              },
              {
                type: "image",
                name: "photo",
                label: "Photo",
              },
              {
                type: "object",
                list: true,
                name: "paragraphs",
                label: "Paragraphs",
                ui: {
                  itemProps: (item) => ({ label: item?.text?.substring(0, 50) || "Paragraph" }),
                },
                fields: [
                  {
                    type: "rich-text",
                    name: "text",
                    label: "Text",
                    ui: {
                      description:
                        "Select a word or sentence and click Bold to emphasize just that part.",
                    },
                  },
                  {
                    type: "string",
                    name: "font_family",
                    label: "Font",
                    options: [
                      { label: "Use Site Default", value: "default" },
                      { label: "Playfair Display", value: "playfair" },
                      { label: "Montserrat", value: "montserrat" },
                      { label: "Poppins", value: "poppins" },
                      { label: "Merriweather", value: "merriweather" },
                      { label: "Lato", value: "lato" },
                    ],
                    ui: { component: "select" },
                  },
                  {
                    type: "string",
                    name: "text_size",
                    label: "Size",
                    options: [
                      { label: "Use Site Default", value: "default" },
                      { label: "Small", value: "small" },
                      { label: "Medium", value: "medium" },
                      { label: "Large", value: "large" },
                    ],
                    ui: { component: "select" },
                  },
                  {
                    type: "string",
                    name: "text_color",
                    label: "Color",
                    options: [
                      { label: "Use Site Default", value: "default" },
                      { label: "Black", value: "black" },
                      { label: "Charcoal", value: "charcoal" },
                      { label: "Grey", value: "grey" },
                      { label: "White", value: "white" },
                      { label: "Navy Blue", value: "navy" },
                      { label: "Blue", value: "blue" },
                      { label: "Dark Green", value: "darkgreen" },
                      { label: "Green", value: "green" },
                      { label: "Red", value: "red" },
                      { label: "Brown", value: "brown" },
                    ],
                    ui: { component: "select" },
                  },
                  {
                    type: "string",
                    name: "text_color_custom",
                    label: "Custom Color (Optional)",
                    ui: {
                      description: "Paste a hex code here to override the color above, or leave blank.",
                    },
                  },
                ],
              },
            ],
          },
          {
            type: "string",
            name: "accent_color",
            label: "Accent Panel Color",
            ui: {
              description:
                "The color behind the text panel on this page. Leave blank to use the site's usual beige. Applies to all sections on this page.",
            },
          },
        ],
      },
      {
        name: "contact",
        label: "Contact / Connect",
        path: "_content/contact.json",
        format: "json",
        ui: { previewSrc: "/pages/contact.html" },
        fields: [
          { type: "string", name: "heading", label: "Heading", ui: { defaultValue: "Connect" } },
          { type: "string", name: "instagram_handle", label: "Instagram Handle" },
          { type: "string", name: "instagram_url", label: "Instagram URL" },
          { type: "string", name: "facebook_url", label: "Facebook URL" },
          { type: "string", name: "email", label: "Email Address" },
          { type: "string", name: "phone", label: "Phone Number" },
          { type: "image", name: "portrait", label: "Portrait Photo" },
          {
            type: "string",
            name: "accent_color",
            label: "Accent Panel Color",
            ui: {
              description:
                "The color behind the text panel on this page. Leave blank to use the site's usual beige.",
            },
          },
        ],
      },
      {
        name: "about",
        label: "Home / About Page",
        path: "_content/about.json",
        format: "json",
        fields: [
          {
            type: "string",
            name: "popup_heading",
            label: "Newsletter Popup Heading",
            ui: { defaultValue: "Notes from Marie's Studio" },
          },
          {
            type: "string",
            name: "popup_body",
            label: "Newsletter Popup Body Text",
            ui: {
              component: "textarea",
              defaultValue:
                "Subscribe to receive notes from Marie Hartig's studio — glimpses of works in progress, stories behind each piece, and the inspirations that shape her murals and canvases.",
            },
          },
          {
            type: "string",
            name: "popup_button",
            label: "Newsletter Button Text",
            ui: { defaultValue: "Subscribe" },
          },
        ],
      },
      {
        name: "process",
        label: "Process Page",
        path: "_content/process.json",
        format: "json",
        ui: { previewSrc: "/pages/process.html" },
        fields: [
          {
            type: "object",
            name: "how_marie_works",
            label: "How Marie Works",
            fields: [
              { type: "string", name: "heading", label: "Heading" },
              { type: "image", name: "photo", label: "Photo" },
              {
                type: "object",
                list: true,
                name: "paragraphs",
                label: "Paragraphs",
                ui: {
                  itemProps: (item) => ({ label: item?.text?.substring(0, 50) || "Paragraph" }),
                },
                fields: [
                  {
                    type: "rich-text",
                    name: "text",
                    label: "Text",
                    ui: {
                      description:
                        "Select a word or sentence and click Bold to emphasize just that part.",
                    },
                  },
                  {
                    type: "string",
                    name: "font_family",
                    label: "Font",
                    options: [
                      { label: "Use Site Default", value: "default" },
                      { label: "Playfair Display", value: "playfair" },
                      { label: "Montserrat", value: "montserrat" },
                      { label: "Poppins", value: "poppins" },
                      { label: "Merriweather", value: "merriweather" },
                      { label: "Lato", value: "lato" },
                    ],
                    ui: { component: "select" },
                  },
                  {
                    type: "string",
                    name: "text_size",
                    label: "Size",
                    options: [
                      { label: "Use Site Default", value: "default" },
                      { label: "Small", value: "small" },
                      { label: "Medium", value: "medium" },
                      { label: "Large", value: "large" },
                    ],
                    ui: { component: "select" },
                  },
                  {
                    type: "string",
                    name: "text_color",
                    label: "Color",
                    options: [
                      { label: "Use Site Default", value: "default" },
                      { label: "Black", value: "black" },
                      { label: "Charcoal", value: "charcoal" },
                      { label: "Grey", value: "grey" },
                      { label: "White", value: "white" },
                      { label: "Navy Blue", value: "navy" },
                      { label: "Blue", value: "blue" },
                      { label: "Dark Green", value: "darkgreen" },
                      { label: "Green", value: "green" },
                      { label: "Red", value: "red" },
                      { label: "Brown", value: "brown" },
                    ],
                    ui: { component: "select" },
                  },
                  {
                    type: "string",
                    name: "text_color_custom",
                    label: "Custom Color (Optional)",
                    ui: {
                      description: "Paste a hex code here to override the color above, or leave blank.",
                    },
                  },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "process",
            label: "Process Steps",
            fields: [
              { type: "string", name: "heading", label: "Heading" },
              { type: "image", name: "photo", label: "Photo" },
              { type: "string", name: "intro", label: "Intro Line" },
              {
                type: "object",
                list: true,
                name: "steps",
                label: "Steps",
                ui: {
                  itemProps: (item) => ({ label: item?.text?.substring(0, 50) || "Step" }),
                },
                fields: [
                  {
                    type: "rich-text",
                    name: "text",
                    label: "Text",
                    ui: {
                      description:
                        "Select a word or sentence and click Bold to emphasize just that part.",
                    },
                  },
                  {
                    type: "string",
                    name: "font_family",
                    label: "Font",
                    options: [
                      { label: "Use Site Default", value: "default" },
                      { label: "Playfair Display", value: "playfair" },
                      { label: "Montserrat", value: "montserrat" },
                      { label: "Poppins", value: "poppins" },
                      { label: "Merriweather", value: "merriweather" },
                      { label: "Lato", value: "lato" },
                    ],
                    ui: { component: "select" },
                  },
                  {
                    type: "string",
                    name: "text_size",
                    label: "Size",
                    options: [
                      { label: "Use Site Default", value: "default" },
                      { label: "Small", value: "small" },
                      { label: "Medium", value: "medium" },
                      { label: "Large", value: "large" },
                    ],
                    ui: { component: "select" },
                  },
                  {
                    type: "string",
                    name: "text_color",
                    label: "Color",
                    options: [
                      { label: "Use Site Default", value: "default" },
                      { label: "Black", value: "black" },
                      { label: "Charcoal", value: "charcoal" },
                      { label: "Grey", value: "grey" },
                      { label: "White", value: "white" },
                      { label: "Navy Blue", value: "navy" },
                      { label: "Blue", value: "blue" },
                      { label: "Dark Green", value: "darkgreen" },
                      { label: "Green", value: "green" },
                      { label: "Red", value: "red" },
                      { label: "Brown", value: "brown" },
                    ],
                    ui: { component: "select" },
                  },
                  {
                    type: "string",
                    name: "text_color_custom",
                    label: "Custom Color (Optional)",
                    ui: {
                      description: "Paste a hex code here to override the color above, or leave blank.",
                    },
                  },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "investment",
            label: "Investment",
            fields: [
              { type: "string", name: "heading", label: "Heading" },
              { type: "image", name: "photo", label: "Photo" },
              { type: "string", name: "intro", label: "Intro Line" },
              {
                type: "object",
                list: true,
                name: "points",
                label: "Points",
                ui: {
                  itemProps: (item) => ({ label: item?.text?.substring(0, 50) || "Point" }),
                },
                fields: [
                  {
                    type: "rich-text",
                    name: "text",
                    label: "Text",
                    ui: {
                      description:
                        "Select a word or sentence and click Bold to emphasize just that part.",
                    },
                  },
                  {
                    type: "string",
                    name: "font_family",
                    label: "Font",
                    options: [
                      { label: "Use Site Default", value: "default" },
                      { label: "Playfair Display", value: "playfair" },
                      { label: "Montserrat", value: "montserrat" },
                      { label: "Poppins", value: "poppins" },
                      { label: "Merriweather", value: "merriweather" },
                      { label: "Lato", value: "lato" },
                    ],
                    ui: { component: "select" },
                  },
                  {
                    type: "string",
                    name: "text_size",
                    label: "Size",
                    options: [
                      { label: "Use Site Default", value: "default" },
                      { label: "Small", value: "small" },
                      { label: "Medium", value: "medium" },
                      { label: "Large", value: "large" },
                    ],
                    ui: { component: "select" },
                  },
                  {
                    type: "string",
                    name: "text_color",
                    label: "Color",
                    options: [
                      { label: "Use Site Default", value: "default" },
                      { label: "Black", value: "black" },
                      { label: "Charcoal", value: "charcoal" },
                      { label: "Grey", value: "grey" },
                      { label: "White", value: "white" },
                      { label: "Navy Blue", value: "navy" },
                      { label: "Blue", value: "blue" },
                      { label: "Dark Green", value: "darkgreen" },
                      { label: "Green", value: "green" },
                      { label: "Red", value: "red" },
                      { label: "Brown", value: "brown" },
                    ],
                    ui: { component: "select" },
                  },
                  {
                    type: "string",
                    name: "text_color_custom",
                    label: "Custom Color (Optional)",
                    ui: {
                      description: "Paste a hex code here to override the color above, or leave blank.",
                    },
                  },
                ],
              },
            ],
          },
          {
            type: "string",
            name: "accent_color",
            label: "Accent Panel Color",
            ui: {
              description:
                "The color behind the text panel on this page. Leave blank to use the site's usual beige. Applies to all three sections on this page.",
            },
          },
        ],
      },
      {
        name: "shop-tattoos",
        label: "Shop — Wall Tattoos",
        path: "_content/shop-tattoos.json",
        format: "json",
        fields: [
          {
            type: "string",
            name: "heading",
            label: "Page Heading",
            ui: { defaultValue: "Wall Tattoos" },
          },
          {
            type: "number",
            name: "price",
            label: "Price per Tattoo (€)",
            ui: { step: 0.01, defaultValue: 45.0 },
          },
          {
            type: "object",
            list: true,
            name: "tattoos",
            label: "Tattoos",
            ui: { itemProps: (item) => ({ label: item?.name || "Tattoo" }) },
            fields: [
              { type: "string", name: "name", label: "Name", ui: { description: "e.g. Wall Tattoo 1" } },
              { type: "image", name: "image", label: "Image" },
              {
                type: "number",
                name: "price",
                label: "Price (€)",
                ui: { step: 0.01 },
              },
            ],
          },
        ],
      },
      {
        name: "shop-prints",
        label: "Shop — Art Prints",
        path: "_content/shop-prints.json",
        format: "json",
        fields: [
          {
            type: "string",
            name: "heading",
            label: "Page Heading",
            ui: { defaultValue: "Art Prints" },
          },
          {
            type: "number",
            name: "price",
            label: "Default Price per Print (€)",
            ui: { step: 0.01, defaultValue: 35.0 },
          },
          {
            type: "object",
            list: true,
            name: "prints",
            label: "Prints",
            ui: { itemProps: (item) => ({ label: item?.name || "Print" }) },
            fields: [
              { type: "string", name: "name", label: "Name", ui: { description: "e.g. Celosia" } },
              { type: "image", name: "image", label: "Image" },
              {
                type: "number",
                name: "price",
                label: "Price (€)",
                ui: { step: 0.01 },
              },
            ],
          },
        ],
      },
      {
        name: "shop-wallpapers",
        label: "Shop — Wallpapers",
        path: "_content/shop-wallpapers.json",
        format: "json",
        fields: [
          {
            type: "string",
            name: "heading",
            label: "Page Heading",
            ui: { defaultValue: "Wallpapers" },
          },
          {
            type: "number",
            name: "price",
            label: "Default Price per Wallpaper (€)",
            ui: { step: 0.01, defaultValue: 120.0 },
          },
          {
            type: "object",
            list: true,
            name: "wallpapers",
            label: "Wallpapers",
            ui: { itemProps: (item) => ({ label: item?.name || "Wallpaper" }) },
            fields: [
              {
                type: "string",
                name: "name",
                label: "Name",
                ui: { description: "e.g. Wallpaper 1" },
              },
              { type: "image", name: "image", label: "Image" },
              {
                type: "number",
                name: "price",
                label: "Price (€)",
                ui: { step: 0.01 },
              },
            ],
          },
        ],
      },
      {
        name: "slideshow-opening",
        label: "Opening Page Slideshow",
        path: "_content/slideshow-opening.json",
        format: "json",
        fields: [
          {
            type: "object",
            list: true,
            name: "slides",
            label: "Slides",
            ui: { itemProps: (item) => ({ label: item?.image || "Slide" }) },
            fields: [
              {
                type: "image",
                name: "image",
                label: "Image",
              },
            ],
          },
        ],
      },
      {
        name: "slideshow-home",
        label: "Home Page Slideshow",
        path: "_content/slideshow-home.json",
        format: "json",
        fields: [
          {
            type: "object",
            list: true,
            name: "slides",
            label: "Slides",
            ui: { itemProps: (item) => ({ label: item?.image || "Slide" }) },
            fields: [
              {
                type: "image",
                name: "image",
                label: "Image",
              },
            ],
          },
        ],
      },
      {
        name: "site-design",
        label: "Site Design",
        path: "_content/site-design.json",
        format: "json",
        ui: { previewSrc: "/" },
        fields: [
          {
            type: "string",
            name: "text_size",
            label: "Text Size",
            options: ["small", "medium", "large"],
            ui: {
              component: "select",
              description:
                "Applies to headings and body text everywhere — titles, descriptions, paragraphs. Does not affect the navigation bar or the homepage/welcome page slideshows.",
            },
          },
          {
            type: "string",
            name: "font_family",
            label: "Font",
            options: [
              { label: "Original (Velour + Jost)", value: "default" },
              { label: "Playfair Display", value: "playfair" },
              { label: "Montserrat", value: "montserrat" },
              { label: "Poppins", value: "poppins" },
              { label: "Merriweather", value: "merriweather" },
              { label: "Lato", value: "lato" },
            ],
            ui: {
              component: "select",
              description:
                "Applies to headings and body text everywhere. Does not affect the navigation bar or the homepage/welcome page slideshows.",
            },
          },
          {
            type: "string",
            name: "text_color",
            label: "Text Color",
            options: [
              { label: "Default", value: "default" },
              { label: "Black", value: "black" },
              { label: "Charcoal", value: "charcoal" },
              { label: "Grey", value: "grey" },
              { label: "White", value: "white" },
              { label: "Navy Blue", value: "navy" },
              { label: "Blue", value: "blue" },
              { label: "Dark Green", value: "darkgreen" },
              { label: "Green", value: "green" },
              { label: "Red", value: "red" },
              { label: "Brown", value: "brown" },
            ],
            ui: {
              component: "select",
              description:
                "Pick a color, or use the custom hex code field below to enter any color you find online.",
            },
          },
          {
            type: "string",
            name: "text_color_custom",
            label: "Custom Color (Optional)",
            ui: {
              description:
                "Paste a hex color code here (e.g., #ffffff for white, #ff0000 for red) or leave blank",
            },
          },
          {
            type: "string",
            name: "background_color",
            label: "Page Background Color",
            ui: {
              description:
                "The backdrop color behind text on every page. Use a hex code — ask your web developer if you're not sure what that means. e.g. #ffffff is pure white, #fdfcfa is a very soft warm white.",
            },
          },
        ],
      },
    ],
  },
});
